export const ExpenseCategories = [
  { name: 'Alimentation', icon: 'coffee' },
  { name: 'Technologie', icon: 'laptop' },
  { name: 'Téléphone', icon: 'mobile' },
  { name: 'Services publics', icon: 'thunderbolt' },
  { name: 'Transport', icon: 'car' },
  { name: 'Loyer', icon: 'home' },
  { name: 'Divertissement', icon: 'play-circle' },
  { name: 'Santé', icon: 'medicine-box' },
  { name: 'Vêtements', icon: 'skin' },
  { name: 'Éducation', icon: 'book' },
  { name: 'Voyages', icon: 'plane' },
  { name: 'Assurance', icon: 'safety-certificate' },
  { name: 'Cadeaux', icon: 'gift' },
  { name: 'Amélioration de la maison', icon: 'tool' },
  { name: 'Loisirs', icon: 'trophy' },
  { name: 'Épicerie', icon: 'shopping-cart' },
  { name: 'Charité', icon: 'heart' },
  { name: 'Animaux domestiques', icon: 'dog' },
  { name: 'Épargne', icon: 'bank' },
  { name: 'Dîner à l\'extérieur', icon: 'restaurant' },
  { name: 'Fitness', icon: 'dumbbell' },
  { name: 'Beauté', icon: 'smile' },
  { name: 'Impôts', icon: 'file-text' },
  { name: 'Remboursement de dettes', icon: 'credit-card' },
  { name: 'Autre', icon: 'question-circle' },
];
